# Generated by Django 5.0.9 on 2025-08-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IRSPublication1494",
            new_name="IRSPublication",
        ),
        migrations.AlterField(
            model_name="withholdinglimit",
            name="wl",
            field=models.IntegerField(),
        ),
    ]
