# Generated by Django 5.0.9 on 2025-08-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0003_rename_irspublication1494_irspublication_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exemptconfig",
            name="ftb_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
