# Generated by Django 5.0.9 on 2025-08-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0004_exemptconfig_ftb_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="withholdinglimit",
            options={},
        ),
        migrations.AlterModelOptions(
            name="withholdingrules",
            options={},
        ),
        migrations.AddField(
            model_name="withholdinglimit",
            name="issusing_state",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="withholdinglimit",
            name="work_state",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="withholdinglimit",
            name="wl",
            field=models.CharField(max_length=10),
        ),
    ]
