# Generated by Django 5.0.9 on 2025-08-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0005_alter_withholdinglimit_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="withholdinglimit",
            old_name="issusing_state",
            new_name="issuing_state",
        ),
    ]
