# Generated by Django 5.0.9 on 2025-09-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0006_rename_issusing_state_withholdinglimit_issuing_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditordebtexemptamtconfig',
            name='state_config',
        ),
    ]
