# Generated by Django 5.0.9 on 2025-09-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0007_remove_creditordebtexemptamtconfig_state_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemptrule',
            name='rule_id',
        ),
    ]
