# Generated by Django 5.0.9 on 2025-09-09 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0008_remove_exemptrule_rule_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSWithholdingPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority_of_withholding", models.CharField(max_length=255)),
                ("status", models.BooleanField(default=True, max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "cs_withholding_priority",
                "db_table": "cs_withholding_priority",
            },
        ),
        migrations.CreateModel(
            name="ChildSupportPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority_order", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CSPriority",
                        to="processor.state",
                    ),
                ),
                (
                    "priority_of_withholding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CSPriority",
                        to="processor.cswithholdingpriority",
                    ),
                ),
            ],
            options={
                "verbose_name": "child_support_priority",
                "db_table": "child_support_priority",
            },
        ),
    ]
