# Generated by Django 5.0.9 on 2025-09-13 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0009_cswithholdingpriority_childsupportpriority"),
    ]

    operations = [
        migrations.CreateModel(
            name="deductions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("status", models.BooleanField(default=True, max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "deductions",
                "db_table": "deductions",
            },
        ),
        migrations.RemoveField(
            model_name="childsupportpriority",
            name="priority_of_withholding",
        ),
        migrations.AddField(
            model_name="childsupportpriority",
            name="deduction_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="CSPriority",
                to="processor.deductions",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CSWithholdingPriority",
        ),
    ]
