# Generated by Django 5.0.9 on 2025-09-17 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0010_deductions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exemptconfig",
            name="rule",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="processor.exemptrule",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="childsupportpriority",
            name="deduction_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="priority_deduction_type",
                to="processor.deductions",
            ),
        ),
        migrations.AlterField(
            model_name="childsupportpriority",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="priority_state",
                to="processor.state",
            ),
        ),
    ]
