# Generated by Django 5.0.9 on 2025-09-17 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0011_exemptconfig_rule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exemptrule",
            name="pay_period",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to="processor.payperiod",
            ),
            preserve_default=False,
        ),
    ]
