# Generated by Django 5.0.9 on 2025-09-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0012_exemptrule_garnishment_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChildSupportPriority",
            new_name="DeductionPriority",
        ),
        migrations.RenameModel(
            old_name="PriorityOrders",
            new_name="MultipleGarnPriorityOrders",
        ),
        migrations.AlterModelOptions(
            name="multiplegarnpriorityorders",
            options={"verbose_name": "multiple_garn_priority_order"},
        ),
        migrations.AlterModelTable(
            name="multiplegarnpriorityorders",
            table="multiple_garn_priority_order",
        ),
    ]
