# Generated by Django 5.0.9 on 2025-09-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0012_exemptrule_pay_period"),
        ("processor", "0013_rename_childsupportpriority_deductionpriority_and_more"),
    ]

    operations = []
