# Generated by Django 5.0.9 on 2025-09-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0014_merge_20250923_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemptrule',
            name='pay_period',
        ),
    ]
