# Generated by Django 5.0.9 on 2025-10-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0015_remove_exemptrule_pay_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exemptconfig",
            name="is_home_state_resident",
        ),
        migrations.AddField(
            model_name="exemptconfig",
            name="home_state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
