# Generated by Django 5.0.9 on 2025-10-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0016_remove_exemptconfig_is_home_state_resident_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exemptconfig",
            name="start_gt_5dec24",
        ),
        migrations.AddField(
            model_name="exemptconfig",
            name="garn_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
