# Generated by Django 5.0.9 on 2025-10-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0017_remove_exemptconfig_start_gt_5dec24_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="thresholdamount",
            name="gp_lower_threshold_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="thresholdamount",
            name="gp_lower_threshold_percent1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
