# Generated by Django 5.0.9 on 2025-11-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0018_thresholdamount_gp_lower_threshold_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditordebtrule",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="creditordebtruleeditpermission",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
