# Generated by Django 5.0.9 on 2025-11-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0020_addexemptions_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exemptconfig",
            name="effective_date",
            field=models.DateField(
                blank=True,
                help_text="Date when this configuration becomes active. If null, config is active immediately.",
                null=True,
            ),
        ),
    ]
