# Generated by Django 5.0.9 on 2025-11-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0023_reset_threshold_amount_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="deductionpriority",
            name="effective_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="garnishmentfees",
            name="effective_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="multiplegarnpriorityorders",
            name="effective_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="multiplegarnpriorityorders",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="withholdinglimit",
            name="effective_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
