# Generated by Django 5.0.9 on 2025-11-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0024_deductionpriority_effective_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="garnishmentfeesrules",
            name="effective_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
