# Generated by Django 5.0.9 on 2025-11-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0026_extend_job_execution_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="GarnishmentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.CharField(max_length=20)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("ee_id", models.CharField(max_length=20)),
                ("case_id", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "gross_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_mandatory_deduction",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "disposable_earning",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "allowable_disposable_earning",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ordered_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "arrear_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "withholding_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "withholding_arrear",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "garnishment_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "withholding_limit_rule",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "withholding_basis",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "withholding_cap",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("garnishment_fees_note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "garnishment_result",
                "ordering": ["-created_at"],
            },
        ),
    ]
