# Generated by Django 5.0.9 on 2025-11-08 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0027_garnishmentresult"),
        ("user_app", "0026_remove_lettertemplate_variables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garnishmentresult",
            name="case_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="garnishment_results",
                to="user_app.garnishmentorder",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="garnishmentresult",
            name="ee_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="garnishment_results",
                to="user_app.employeedetail",
            ),
        ),
        migrations.AlterField(
            model_name="garnishmentresult",
            name="garnishment_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="garnishment_results",
                to="processor.garnishmenttype",
            ),
            preserve_default=False,
        ),
    ]
