# Generated by Django 5.0.9 on 2025-11-10 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0028_alter_garnishmentresult_case_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="garnishmentresult",
            old_name="case_id",
            new_name="case",
        ),
        migrations.RenameField(
            model_name="garnishmentresult",
            old_name="ee_id",
            new_name="ee",
        ),
    ]
