# Generated by Django 5.0.9 on 2025-11-10 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0029_rename_case_id_garnishmentresult_case_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="statetaxlevyexemptamtconfig",
            new_name="state_tax_l_pay_per_9eb24f_idx",
            old_name="state_tax_l_pay_per_53e09d_idx",
        ),
        migrations.AlterField(
            model_name="statetaxlevyexemptamtconfig",
            name="pay_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="processor.payperiod"
            ),
        ),
    ]
