# Generated by Django 5.0.9 on 2025-11-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0030_rename_state_tax_l_pay_per_53e09d_idx_state_tax_l_pay_per_9eb24f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garnishmenttype',
            name='code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garnishmenttype',
            name='pay_stub_description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garnishmenttype',
            name='report_description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
