# Generated by Django 5.0.9 on 2025-11-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0031_garnishmenttype_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garnishmenttype',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
