# Generated by Django 5.0.9 on 2025-11-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0032_alter_garnishmenttype_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garnishmentresult',
            name='withholding_limit_rule',
        ),
        migrations.AddField(
            model_name='garnishmentresult',
            name='withholding_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
