# Generated by Django 5.0.9 on 2025-11-17 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0033_remove_garnishmentresult_withholding_limit_rule_and_more'),
        ('user_app', '0042_remove_employeedetail_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50)),
                ('pay_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('check_number', models.CharField(blank=True, max_length=50, null=True)),
                ('check_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ach_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('eft_check', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment', models.TextField(blank=True, help_text='Additional comments or notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='user_app.garnishmentorder')),
                ('ee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='user_app.employeedetail')),
            ],
            options={
                'verbose_name': 'payment_history',
                'verbose_name_plural': 'payment_histories',
                'db_table': 'payment_history',
                'ordering': ['-pay_date', '-created_at'],
                'indexes': [models.Index(fields=['ee'], name='payment_his_ee_id_48469b_idx'), models.Index(fields=['case'], name='payment_his_case_id_178413_idx'), models.Index(fields=['pay_date'], name='payment_his_pay_dat_486e3f_idx'), models.Index(fields=['voucher_number'], name='payment_his_voucher_497d1e_idx')],
            },
        ),
    ]
