# Generated by Django 5.0.9 on 2025-01-XX XX:XX

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0034_paymenthistory'),
        ('user_app', '0042_remove_employeedetail_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50)),
                ('pay_date', models.DateField()),
                ('deduction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('check_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ach_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('void_check', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_history', to='user_app.garnishmentorder')),
            ],
            options={
                'verbose_name': 'deduction_history',
                'verbose_name_plural': 'deduction_histories',
                'db_table': 'deduction_history',
                'ordering': ['-pay_date', '-created_at'],
                'indexes': [
                    models.Index(fields=['case'], name='deduction_his_case_id_idx'),
                    models.Index(fields=['pay_date'], name='deduction_his_pay_dat_idx'),
                    models.Index(fields=['voucher_number'], name='deduction_his_voucher_idx'),
                    models.Index(fields=['void_check'], name='deduction_his_void_ch_idx'),
                ],
            },
        ),
    ]

