# Generated by Django 5.0.9 on 2025-11-21 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0035_deductionhistory'),
        ('user_app', '0066_rename_originating_bank_name_achgarnishmentconfig_peos_bank_name_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deductionhistory',
            new_name='deduction_h_case_id_5a1658_idx',
            old_name='deduction_his_case_id_idx',
        ),
        migrations.RenameIndex(
            model_name='deductionhistory',
            new_name='deduction_h_pay_dat_1de7dd_idx',
            old_name='deduction_his_pay_dat_idx',
        ),
        migrations.RenameIndex(
            model_name='deductionhistory',
            new_name='deduction_h_voucher_a07ce3_idx',
            old_name='deduction_his_voucher_idx',
        ),
        migrations.RenameIndex(
            model_name='deductionhistory',
            new_name='deduction_h_void_ch_2d9068_idx',
            old_name='deduction_his_void_ch_idx',
        ),
        migrations.AlterField(
            model_name='deductionhistory',
            name='ach_reference',
            field=models.CharField(blank=True, help_text='ACH reference number', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deductionhistory',
            name='case',
            field=models.ForeignKey(help_text='Associated garnishment order', on_delete=django.db.models.deletion.CASCADE, related_name='deduction_history', to='user_app.garnishmentorder'),
        ),
        migrations.AlterField(
            model_name='deductionhistory',
            name='check_number',
            field=models.CharField(blank=True, help_text='Check number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deductionhistory',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, help_text='Deduction amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='deductionhistory',
            name='paid_on',
            field=models.DateField(blank=True, help_text='Date when payment was made', null=True),
        ),
        migrations.AlterField(
            model_name='deductionhistory',
            name='pay_date',
            field=models.DateField(help_text='Pay date'),
        ),
        migrations.AlterField(
            model_name='deductionhistory',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Payment amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deductionhistory',
            name='void_check',
            field=models.BooleanField(default=False, help_text='Whether the check is void'),
        ),
        migrations.AlterField(
            model_name='deductionhistory',
            name='voucher_number',
            field=models.CharField(help_text='Voucher number', max_length=50),
        ),
    ]
