# Generated by Django 5.0.9 on 2025-08-31 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0006_rename_issusing_state_withholdinglimit_issuing_state"),
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedetail",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="employeedetail",
            name="filing_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="processor.fedfilingstatus",
            ),
        ),
        migrations.AlterField(
            model_name="employeedetail",
            name="garnishment_fees_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="employeedetail",
            name="garnishment_fees_suspended_till",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employeedetail",
            name="home_state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees_home",
                to="processor.state",
            ),
        ),
        migrations.AlterField(
            model_name="employeedetail",
            name="record_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="employeedetail",
            name="support_second_family",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="employeedetail",
            name="work_state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees_work",
                to="processor.state",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["client_id"], name="client_client__54da13_idx"),
        ),
        migrations.AddIndex(
            model_name="peo",
            index=models.Index(fields=["peo_id"], name="peo_peo_id_bdb676_idx"),
        ),
        migrations.AlterModelTable(
            name="client",
            table="client",
        ),
        migrations.AlterModelTable(
            name="peo",
            table="peo",
        ),
    ]
