# Generated by Django 5.0.9 on 2025-08-31 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_alter_employeedetail_age_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="garnishmentorder",
            name="employer",
        ),
    ]
