# Generated by Django 5.0.9 on 2025-08-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_remove_garnishmentorder_employer"),
    ]

    operations = [
        migrations.AddField(
            model_name="garnishmentorder",
            name="deduction_code",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="garnishment_fees",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="override_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="override_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="override_stop_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="paid_till_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="payee",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sdu",
            name="fips_code",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
