# Generated by Django 5.0.9 on 2025-09-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_garnishmentorder_deduction_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
