# Generated by Django 5.0.9 on 2025-09-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_app",
            "0005_employeedetail_first_name_employeedetail_last_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeedetail",
            name="record_import",
        ),
        migrations.RemoveField(
            model_name="employeedetail",
            name="record_updated",
        ),
    ]
