# Generated by Django 5.0.9 on 2025-09-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_remove_employeedetail_record_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='service_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
