# Generated by Django 5.0.9 on 2025-09-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0012_exemptrule_garnishment_type"),
        ("user_app", "0007_client_service_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sdu",
            name="sdu_order_i_c74db7_idx",
        ),
        migrations.RenameField(
            model_name="sdu",
            old_name="order",
            new_name="case_id",
        ),
        migrations.RenameField(
            model_name="sdu",
            old_name="country",
            new_name="payee",
        ),
        migrations.RemoveField(
            model_name="sdu",
            name="name",
        ),
        migrations.AddField(
            model_name="sdu",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sdu",
            name="contact",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="sdu",
            index=models.Index(fields=["case_id"], name="sdu_case_id_7b49a6_idx"),
        ),
    ]
