# Generated by Django 5.0.9 on 2025-09-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_remove_sdu_sdu_order_i_c74db7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='industry_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='is_blind',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='is_spouse_blind',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='spouse_age',
        ),
    ]
