# Generated by Django 5.0.9 on 2025-09-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0009_remove_client_industry_type_remove_client_tax_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="garnishmentorder",
            name="arrear_gt_12_weeks",
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="current_child_support",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="current_medical_support",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="current_spousal_support",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="fips_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="medical_support_arrear",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="spousal_support_arrear",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="garnishmentorder",
            name="withholding_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
    ]
