# Generated by Django 5.0.9 on 2025-09-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0010_remove_garnishmentorder_arrear_gt_12_weeks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="garnishmentorder",
            name="work_state",
        ),
    ]
