# Generated by Django 5.0.9 on 2025-09-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0011_remove_garnishmentorder_work_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garnishmentorder",
            name="garnishing_authority",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="garnishmentorder",
            name="payee",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
