# Generated by Django 5.0.9 on 2025-09-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0012_alter_garnishmentorder_garnishing_authority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="garnishmentorder",
            name="child_support_arrear",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
