# Generated by Django 5.0.9 on 2025-09-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0013_garnishmentorder_child_support_arrear"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garnishmentorder",
            name="override_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
