# Generated by Django 5.0.9 on 2025-10-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0014_alter_garnishmentorder_override_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="dba",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
