# Generated by Django 5.0.9 on 2025-10-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0015_alter_client_dba"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="pay_period",
        ),
    ]
