# Generated by Django 5.0.9 on 2025-10-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0016_remove_client_pay_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedetail",
            name="garnishment_fees_status",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="employeedetail",
            name="number_of_active_garnishment",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
