# Generated by Django 5.0.9 on 2025-10-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0018_employeedetails"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeDetails",
        ),
    ]
