# Generated by Django 5.0.9 on 2025-10-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0017_remove_exemptconfig_start_gt_5dec24_and_more"),
        ("user_app", "0019_delete_employeedetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ee_id", models.CharField(max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=255)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("ssn", models.CharField(max_length=64)),
                ("gender", models.CharField(blank=True, max_length=255, null=True)),
                ("number_of_exemptions", models.IntegerField()),
                ("marital_status", models.CharField(max_length=255)),
                ("number_of_student_default_loan", models.IntegerField()),
                ("number_of_dependent_child", models.IntegerField()),
                ("support_second_family", models.BooleanField(default=False)),
                (
                    "garnishment_fees_status",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "garnishment_fees_suspended_till",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "number_of_active_garnishment",
                    models.IntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="user_app.client",
                    ),
                ),
                (
                    "filing_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="processor.fedfilingstatus",
                    ),
                ),
                (
                    "home_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees_home",
                        to="processor.state",
                    ),
                ),
                (
                    "work_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees_work",
                        to="processor.state",
                    ),
                ),
            ],
            options={
                "db_table": "employee_details",
                "indexes": [
                    models.Index(fields=["ee_id"], name="employee_de_ee_id_115302_idx")
                ],
            },
        ),
    ]
