# Generated by Django 5.0.9 on 2025-10-16 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0020_rename_employeedetail_employeedetails_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payroll",
            name="ee_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payrolls",
                to="user_app.employeedetails",
            ),
        ),
        migrations.AlterField(
            model_name="garnishmentorder",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="garnishments",
                to="user_app.employeedetails",
            ),
        ),
        migrations.AlterField(
            model_name="iwodetailspdf",
            name="ee_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="IWODetailsPDF",
                to="user_app.employeedetails",
            ),
        ),
    ]
