# Generated by Django 5.0.9 on 2025-10-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_app",
            "0021_alter_payroll_ee_id_alter_garnishmentorder_employee_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeDetail",
        ),
    ]
