# Generated by Django 5.0.9 on 2025-10-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0017_remove_exemptconfig_start_gt_5dec24_and_more"),
        ("user_app", "0022_delete_employeedetail"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmployeeDetails",
            new_name="EmployeeDetail",
        ),
        migrations.RenameIndex(
            model_name="employeedetail",
            new_name="employee_de_ee_id_3472c7_idx",
            old_name="employee_de_ee_id_115302_idx",
        ),
        migrations.AlterModelTable(
            name="employeedetail",
            table="employee_detail",
        ),
    ]
