# Generated by Django 5.0.9 on 2025-10-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0023_rename_employeedetails_employeedetail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="garnishmentorder",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
