# Generated by Django 5.0.9 on 2025-11-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0024_garnishmentorder_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the letter template', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the letter template', null=True)),
                ('html_content', models.TextField(help_text='HTML content of the letter template with variable placeholders like {{variable_name}}')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='JSON object containing variable definitions and their default values')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the template is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'letter_template',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='letter_temp_name_bf8605_idx'), models.Index(fields=['is_active'], name='letter_temp_is_acti_34c5b0_idx')],
            },
        ),
    ]
