# Generated by Django 5.0.9 on 2025-11-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0025_lettertemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lettertemplate',
            name='variables',
        ),
    ]
