# Generated by Django 5.0.9 on 2025-11-10 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "processor",
            "0030_rename_state_tax_l_pay_per_53e09d_idx_state_tax_l_pay_per_9eb24f_idx_and_more",
        ),
        ("user_app", "0026_remove_lettertemplate_variables"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayeeDetails",
            fields=[
                ("payee_id", models.AutoField(primary_key=True, serialize=False)),
                ("payee_type", models.CharField(max_length=100)),
                ("payee", models.CharField(max_length=255)),
                (
                    "routing_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "bank_account",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("case_number_required", models.BooleanField(default=False)),
                (
                    "case_number_format",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fips_required", models.BooleanField(default=False)),
                ("fips_length", models.IntegerField(blank=True, null=True)),
                ("last_used", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sdus",
                        to="user_app.garnishmentorder",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sdus",
                        to="processor.state",
                    ),
                ),
            ],
            options={
                "db_table": "payee_details",
            },
        ),
        migrations.CreateModel(
            name="PayeeAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_1", models.CharField(blank=True, max_length=255, null=True)),
                ("address_2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                ("zip_plus_4", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "payee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="user_app.payeedetails",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payee Address",
                "verbose_name_plural": "Payee Addresses",
                "db_table": "payee_address",
            },
        ),
        migrations.DeleteModel(
            name="SDU",
        ),
        migrations.AddIndex(
            model_name="payeedetails",
            index=models.Index(
                fields=["state_id"], name="payee_detai_state_i_32957b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payeedetails",
            index=models.Index(
                fields=["case_id"], name="payee_detai_case_id_faf421_idx"
            ),
        ),
    ]
