# Generated by Django 5.0.9 on 2025-11-10 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "processor",
            "0030_rename_state_tax_l_pay_per_53e09d_idx_state_tax_l_pay_per_9eb24f_idx_and_more",
        ),
        ("user_app", "0027_payeedetails_payeeaddress_delete_sdu_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payeedetails",
            name="payee_detai_state_i_32957b_idx",
        ),
        migrations.RemoveField(
            model_name="payeedetails",
            name="state",
        ),
        migrations.AlterField(
            model_name="payeeaddress",
            name="state",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payee_addresses",
                to="processor.state",
            ),
            preserve_default=False,
        ),
    ]
