# Generated by Django 5.0.9 on 2025-11-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0028_remove_payeedetails_payee_detai_state_i_32957b_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payeedetails',
            index=models.Index(fields=['payee_id'], name='payee_detai_payee_i_606fff_idx'),
        ),
    ]
