# Generated by Django 5.0.9 on 2025-11-11 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0029_payeedetails_payee_detai_payee_i_606fff_idx"),
    ]

    operations = [
        migrations.RenameField(
            model_name="garnishmentorder",
            old_name="withholding_amount",
            new_name="amount_of_deduction",
        ),
        migrations.RenameField(
            model_name="garnishmentorder",
            old_name="garnishing_authority",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="garnishmentorder",
            old_name="payee",
            new_name="voucher_for_payroll",
        ),
        migrations.RemoveField(
            model_name="garnishmentorder",
            name="fein",
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="ach_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="ap_check",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="date_of_ap_payment",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="exempt_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="monthly_limit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="override_arrear",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="override_child_support",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="override_child_support_arrear",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="override_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="override_medical_support",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="override_medical_support_arrear",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="override_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="override_spousal_support",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="override_spousal_support_arrear",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="pay_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="pay_period_limit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="total_amount_owed",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="ytd_deductions",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="payeedetails",
            name="case_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sdus",
                to="user_app.garnishmentorder",
            ),
        ),
    ]
