# Generated by Django 5.0.9 on 2025-11-11 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0029_payeedetails_payee_detai_payee_i_606fff_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmplopyeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(max_length=100)),
                ('address1', models.TextField(max_length=255)),
                ('address2', models.TextField(max_length=255)),
                ('zip_Code', models.IntegerField(max_length=6)),
                ('geo_code', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('ee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_addresses', to='user_app.employeedetail')),
            ],
            options={
                'db_table': 'employee_address',
                'indexes': [models.Index(fields=['ee_id'], name='employee_ad_ee_id_6795c6_idx')],
            },
        ),
    ]
