# Generated by Django 5.0.9 on 2025-11-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0030_emplopyeeaddress'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emplopyeeaddress',
            name='employee_ad_ee_id_6795c6_idx',
        ),
        migrations.AlterField(
            model_name='emplopyeeaddress',
            name='geo_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emplopyeeaddress',
            name='zip_Code',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='emplopyeeaddress',
            index=models.Index(fields=['ee'], name='employee_ad_ee_id_6795c6_idx'),
        ),
    ]
