# Generated by Django 5.0.9 on 2025-11-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_app",
            "0030_rename_withholding_amount_garnishmentorder_amount_of_deduction_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="garnishmentorder",
            name="is_active",
        ),
    ]
