# Generated by Django 5.0.9 on 2025-11-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0031_remove_emplopyeeaddress_employee_ad_ee_id_6795c6_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emplopyeeaddress',
            old_name='address1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='emplopyeeaddress',
            old_name='address2',
            new_name='address_2',
        ),
    ]
