# Generated by Django 5.0.9 on 2025-11-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0032_rename_address1_emplopyeeaddress_address_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emplopyeeaddress',
            old_name='zip_Code',
            new_name='zip_code',
        ),
    ]
