# Generated by Django 5.0.9 on 2025-11-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0033_rename_zip_code_emplopyeeaddress_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplopyeeaddress',
            name='address_type',
        ),
    ]
