# Generated by Django 5.0.9 on 2025-11-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0034_remove_emplopyeeaddress_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
