# Generated by Django 5.0.9 on 2025-11-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0031_remove_garnishmentorder_is_active"),
        ("user_app", "0035_employeedetail_status"),
    ]

    operations = []
