# Generated by Django 5.0.9 on 2025-11-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0036_merge_20251112_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="garnishmentorder",
            name="deduction_basis",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employeedetail",
            name="status",
            field=models.CharField(blank=True, default="active", max_length=50),
        ),
        migrations.AlterField(
            model_name="garnishmentorder",
            name="status",
            field=models.CharField(
                blank=True, default="active", max_length=255, null=True
            ),
        ),
    ]
