# Generated by Django 5.0.9 on 2025-11-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0037_add_deduction_basis_to_garnishmentorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="garnishmentorder",
            name="payee_id",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
