# Generated by Django 5.0.9 on 2025-11-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0038_garnishmentorder_payee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettertemplate',
            name='category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lettertemplate',
            name='event_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lettertemplate',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
