# Generated by Django 5.0.9 on 2025-11-14 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0038_garnishmentorder_payee_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ACHFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_format",
                    models.CharField(
                        choices=[("txt", "TXT"), ("pdf", "PDF"), ("xml", "XML")],
                        default="txt",
                        max_length=10,
                    ),
                ),
                ("file_url", models.URLField(blank=True, null=True)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("pay_date", models.DateField()),
                (
                    "agency_payee",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_payment_count", models.IntegerField(default=0)),
                (
                    "total_payment_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("batch_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "file_id_modifier",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("associated_case_ids", models.TextField(blank=True, null=True)),
                ("transaction_references", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_ach_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ach_file",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["pay_date"], name="ach_file_pay_dat_9e0765_idx"
                    ),
                    models.Index(
                        fields=["generated_at"], name="ach_file_generat_7cdbcd_idx"
                    ),
                    models.Index(
                        fields=["batch_id"], name="ach_file_batch_i_2a53c5_idx"
                    ),
                ],
            },
        ),
    ]
