# Generated by Django 5.0.9 on 2025-11-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0039_achfile'),
        ('user_app', '0039_lettertemplate_category_lettertemplate_event_type_and_more'),
    ]

    operations = [
    ]
