# Generated by Django 5.0.9 on 2025-11-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0040_merge_20251117_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplopyeeaddress',
            name='address_2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emplopyeeaddress',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
