# Generated by Django 5.0.9 on 2025-11-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0041_alter_emplopyeeaddress_address_2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeedetail",
            name="is_active",
        ),
    ]
