# Generated by Django 5.0.9 on 2025-11-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0042_remove_employeedetail_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emplopyeeaddress",
            name="address_1",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
