# Generated by Django 5.0.9 on 2025-11-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0043_alter_emplopyeeaddress_address_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="garnishmentorder",
            name="de_range_lower_to_mid_threshold_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="de_range_lower_to_upper_threshold_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="de_range_mid_to_upper_threshold_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="exempt_amt",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="filing_status_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="gp_lower_threshold_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="gp_lower_threshold_percent1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="lower_threshold_percent1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="lower_threshold_percent2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="mid_threshold_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="mid_threshold_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="ower_threshold_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="upper_threshold_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="upper_threshold_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
