# Generated by Django 5.0.9 on 2025-11-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0034_paymenthistory"),
        (
            "user_app",
            "0044_garnishmentorder_de_range_lower_to_mid_threshold_percent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payeedetails",
            name="state",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sdus",
                to="processor.state",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payeedetails",
            name="case_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sdus",
                to="user_app.garnishmentorder",
            ),
        ),
    ]
