# Generated by Django 5.0.9 on 2025-11-18 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0045_payeedetails_state_alter_payeedetails_case_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="garnishmentorder",
            name="payee_id",
        ),
        migrations.AddField(
            model_name="garnishmentorder",
            name="payee",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="garnishment_orders",
                to="user_app.payeedetails",
            ),
            preserve_default=False,
        ),
    ]
