# Generated by Django 5.0.9 on 2025-11-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0046_remove_garnishmentorder_payee_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AchGarnishmentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pay_date", models.DateField()),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("CCD", "CCD"), ("CTX", "CTX"), ("PPD", "PPD")],
                        max_length=3,
                    ),
                ),
                ("garnishment_type", models.CharField(max_length=100)),
                (
                    "medical_support_indicator",
                    models.CharField(
                        choices=[("N", "No"), ("Y", "Yes")], default="N", max_length=1
                    ),
                ),
                (
                    "service_class_code",
                    models.CharField(
                        choices=[
                            ("200", "Credit & Debit"),
                            ("220", "Credits Only"),
                            ("225", "Debits Only"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("checking", "Checking"), ("savings", "Savings")],
                        max_length=10,
                    ),
                ),
                (
                    "transaction_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("22", "Credit"),
                            ("23", "Prenote Credit"),
                            ("27", "Debit"),
                            ("28", "Prenote Debit"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("company_id", models.CharField(max_length=20)),
                (
                    "originating_routing_number",
                    models.CharField(
                        help_text="Immediate receiving routing number", max_length=9
                    ),
                ),
                (
                    "originating_bank_name",
                    models.CharField(default="Wells Fargo Garnishment", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
