# Generated by Django 5.0.9 on 2025-11-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0034_paymenthistory"),
        ("user_app", "0048_rename_payeedetails_payee_id_to_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payeedetails",
            name="payee_detai_payee_i_606fff_idx",
        ),
        migrations.AddIndex(
            model_name="payeedetails",
            index=models.Index(fields=["id"], name="payee_detai_id_622928_idx"),
        ),
    ]
