# Generated by Django 5.0.9 on 2025-11-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_app",
            "0049_remove_payeedetails_payee_detai_payee_i_606fff_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payeedetails",
            name="payee_id",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
