# Generated by Django 5.0.9 on 2025-11-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0050_payeedetails_payee_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payeedetails",
            name="is_active",
        ),
        migrations.AddField(
            model_name="payeedetails",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
