# Generated by Django 5.0.9 on 2025-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0034_paymenthistory"),
        ("user_app", "0051_remove_payeedetails_is_active_payeedetails_status"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payeedetails",
            name="payee_detai_case_id_faf421_idx",
        ),
        migrations.RemoveField(
            model_name="payeedetails",
            name="case_id",
        ),
        migrations.AddIndex(
            model_name="payeedetails",
            index=models.Index(
                fields=["payee_id"], name="payee_detai_payee_i_606fff_idx"
            ),
        ),
    ]
