# Generated by Django 5.0.9 on 2025-11-18 18:57

from django.db import migrations, models


def clean_nan_values(apps, schema_editor):
    """Clean up 'nan' string values before converting to IntegerField"""
    # Use raw SQL to avoid trigger events and ensure efficient bulk updates
    with schema_editor.connection.cursor() as cursor:
        # Clean up 'nan' values (case-insensitive) and empty strings
        # Set them to NULL before converting to integer
        # Handle NULL values properly in WHERE clause
        cursor.execute("""
            UPDATE payee_details 
            SET bank_account = NULL 
            WHERE (bank_account IS NOT NULL AND (
                LOWER(TRIM(bank_account)) = 'nan' 
                OR bank_account = '' 
                OR bank_account !~ '^[0-9]+$'
            ))
        """)
        
        cursor.execute("""
            UPDATE payee_details 
            SET routing_number = NULL 
            WHERE (routing_number IS NOT NULL AND (
                LOWER(TRIM(routing_number)) = 'nan' 
                OR routing_number = '' 
                OR routing_number !~ '^[0-9]+$'
            ))
        """)


def reverse_clean_nan_values(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):
    # Make migration non-atomic to allow data migration to commit before schema change
    atomic = False

    dependencies = [
        (
            "user_app",
            "0052_remove_payeedetails_payee_detai_case_id_faf421_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AchBankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.CharField(max_length=20)),
                (
                    "originating_routing_number",
                    models.CharField(
                        help_text="Immediate receiving routing number", max_length=9
                    ),
                ),
                (
                    "originating_bank_name",
                    models.CharField(default="Wells Fargo Garnishment", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        # Clean up 'nan' values before converting field types
        # This will commit separately due to atomic = False
        migrations.RunPython(clean_nan_values, reverse_clean_nan_values, atomic=True),
        migrations.AlterField(
            model_name="payeedetails",
            name="bank_account",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payeedetails",
            name="routing_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
