# Generated by Django 5.0.9 on 2025-11-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0053_achbankdetails_alter_payeedetails_bank_account_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achgarnishmentconfig",
            name="pay_date",
        ),
    ]
