# Generated by Django 5.0.9 on 2025-11-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0054_remove_achgarnishmentconfig_pay_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achgarnishmentconfig",
            name="garnishment_type",
        ),
    ]
