# Generated by Django 5.0.9 on 2025-11-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0055_remove_achgarnishmentconfig_garnishment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="achgarnishmentconfig",
            name="company_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="achgarnishmentconfig",
            name="file_id_modifier",
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="achgarnishmentconfig",
            name="immediate_destination",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="achgarnishmentconfig",
            name="immediate_origin_name",
            field=models.CharField(default=1, max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="achgarnishmentconfig",
            name="internal_reference_code",
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="achgarnishmentconfig",
            name="originating_dfi_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
