# Generated by Django 5.0.9 on 2025-11-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0056_achgarnishmentconfig_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payeeaddress",
            name="zip_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
