# Generated by Django 5.0.9 on 2025-11-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0057_alter_payeeaddress_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payeedetails",
            name="bank_account",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payeedetails",
            name="routing_number",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
