# Generated by Django 5.0.9 on 2025-11-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0058_alter_payeedetails_bank_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payeedetails",
            name="bank_account",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payeedetails",
            name="routing_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
