# Generated by Django 5.0.9 on 2025-11-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0059_alter_payeedetails_bank_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payeeaddress",
            name="zip_plus_4",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
