# Generated by Django 5.0.9 on 2025-11-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0060_alter_payeeaddress_zip_plus_4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payeedetails",
            name="last_used",
            field=models.CharField(blank=True, null=True),
        ),
    ]
