# Generated by Django 5.0.9 on 2025-11-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0061_alter_payeedetails_last_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payeedetails",
            name="bank_account",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payeedetails",
            name="routing_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
