# Generated by Django 5.0.9 on 2025-11-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0062_alter_payeedetails_routing_bank_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achgarnishmentconfig",
            name="file_id_modifier",
        ),
        migrations.RemoveField(
            model_name="achgarnishmentconfig",
            name="immediate_destination",
        ),
        migrations.RemoveField(
            model_name="achgarnishmentconfig",
            name="immediate_origin_name",
        ),
        migrations.RemoveField(
            model_name="achgarnishmentconfig",
            name="internal_reference_code",
        ),
        migrations.RemoveField(
            model_name="achgarnishmentconfig",
            name="originating_dfi_id",
        ),
        migrations.AlterField(
            model_name="achgarnishmentconfig",
            name="originating_routing_number",
            field=models.CharField(
                help_text="Immediate receiving routing number", max_length=50
            ),
        ),
    ]
