# Generated by Django 5.0.9 on 2025-11-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0063_remove_achgarnishmentconfig_file_id_modifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="achgarnishmentconfig",
            name="peos_bank_routing_number",
            field=models.CharField(
                default=1,
                help_text="PEOs Bank Routing number (Wells Fargo) - Immediate destination",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="achgarnishmentconfig",
            name="transaction_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("22", "Credit"),
                    ("23", "Prenote Credit"),
                    ("27", "Debit"),
                    ("28", "Prenote Debit"),
                    ("32", "Credit"),
                    ("33", "Prenote Credit"),
                    ("37", "Debit"),
                    ("38", "Prenote Debit"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
