# Generated by Django 5.0.9 on 2025-11-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0065_payroll_batch_id_payroll_california_sdi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achgarnishmentconfig',
            old_name='originating_bank_name',
            new_name='peos_bank_name',
        ),
        migrations.RemoveField(
            model_name='achgarnishmentconfig',
            name='originating_routing_number',
        ),
    ]
